[package]
name = "rusqlite-wasm32-unknown-unknown-nix"
version = "0.1.0"
edition = "2018"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rusqlite = { version = "0.26", features = ["bundled"] }